{
 "title": "Pfsense - Firewall",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "iface",
    "label": "Interface",
    "query": "{\"find\": \"terms\", \"field\":\"interface\",\"size\": \"1000000\" }"
   }
  ]
 },
 "panels": [
  {
   "title": "Firewall actions on $iface ",
   "type": "graph",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "action",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "interface:$iface",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top ip Block by $iface",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 9, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "dest_ip",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "dest_ip_city_name",
       "id": "8",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "dest_ip_country_code",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "interface:$iface AND action:block",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total Firewall Events",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "interface:$iface",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Block actions on interface:$iface ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "interface:$iface AND action:block",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Protocols by interface $iface",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 17, "y": 3 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "proto",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "interface:$iface",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Match by interface $iface",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "interface",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "interface:$iface AND reason:match",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top 10 port Destination Block by $iface",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 14, "x": 9, "y": 12 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "Port: {{dest_port_name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "dest_port_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "interface:$iface  AND action:block",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "GeoIP Block source ip location by $iface",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 20 },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "dest_ip",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "dst_location", "id": "2", "settings": { "precision": 7 }, "type": "geohash_grid" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "interface:$iface AND action:block",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Real time logs by interface:$iface ",
   "type": "table",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 31 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 10000 },
       "type": "raw_document"
      }
     ],
     "query": "interface:$iface AND NOT interface:lo0",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Rules triggered on $iface by City",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "none", "label": "Number of accesses" }
   ],
   "targets": [
    {
     "alias": "City: {{term dest_ip_city_name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "dest_ip_city_name",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "timestamp",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "interface:$iface",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Rules triggered on $iface by Country",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "none", "label": "Triggers" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "dest_ip_country_code",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "timestamp",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "interface:$iface",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}